api:
  image: rollforguildinc/elixir
  ports:
    - "4000:4000"
  command: >
    sh -c "mix deps.get
    && mix ecto.create
    && mix ecto.migrate
    && mix phx.server"
  environment:
    - RFG_API_AWS_BUCKET
    - RFG_API_AWS_REGION
    - RFG_API_DB_HOST=postgres
    - RFG_API_DB_NAME
    - RFG_API_DB_PASS
    - RFG_API_DB_PORT
    - RFG_API_DB_USER
    - RFG_API_ENCRYPTION_KEYPHRASE
    - RFG_API_PORT=4000
    - RFG_AWS_ACCESS_KEY_ID
    - RFG_AWS_SECRET_ACCESS_KEY
  volumes:
    - .:/app
  links:
    - postgres
    - elasticsearch
  working_dir: /app

postgres:
  image: mdillon/postgis:10-alpine
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_PASSWORD=${RFG_API_DB_PASS}
    - POSTGRES_USER=${RFG_API_DB_USER}

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
  environment:
    - bootstrap.memory_lock=true
    - cluster.name=rfg_cluster
  ports:
    - "9200:9200"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  volumes:
    - ./elasticsearch-data:/usr/share/elasticsearch/data
